-- Add missing columns to stock table for Polygon metadata
ALTER TABLE incrementum.stock
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS market_cap BIGINT,
ADD COLUMN IF NOT EXISTS primary_exchange VARCHAR(100),
ADD COLUMN IF NOT EXISTS type VARCHAR(50),
ADD COLUMN IF NOT EXISTS currency_name VARCHAR(50),
ADD COLUMN IF NOT EXISTS cik VARCHAR(50),
ADD COLUMN IF NOT EXISTS composite_figi VARCHAR(50),
ADD COLUMN IF NOT EXISTS share_class_figi VARCHAR(50),
ADD COLUMN IF NOT EXISTS outstanding_shares BIGINT,
ADD COLUMN IF NOT EXISTS eps NUMERIC(20, 6),
ADD COLUMN IF NOT EXISTS homepage_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS total_employees INT,
ADD COLUMN IF NOT EXISTS list_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS locale VARCHAR(20),
ADD COLUMN IF NOT EXISTS sic_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS sic_description VARCHAR(255);
